# Perfil base del ingeniero junior. 
# Completa tus datos reales en este archivo. El optimizador de CV adaptará esta información
# a las necesidades de la oferta laboral seleccionada sin añadir experiencia ficticia.

personal_info:
  full_name: "Karen Lizeth Quintero Villasmil"
  email: "karenlizethqv@ufps.edu.co"
  phone: "+57 313 460 5728"
  location: "Cúcuta, Colombia"
  linkedin: "https://linkedin.com/in/karenquintero"
  github: "https://github.com/LizVillasmil"

professional_summary: >
  Ingeniero de Sistemas Junior con fuerte interés en el desarrollo de software,
  sistemas distribuidos y machine learning. Experiencia práctica con proyectos académicos en el área de frontend y 
  ligeramente en backend. Habilidades sólidas en lógica y resolución de problemas, en continuo aprendizaje para mejorar mis competencias ténicas
  y adapatarme a las necesidades del mercado laboral. Busco oportunidades para aplicar mis conocimientos y crecer profesionalmente en un entorno dinámico e innovador.
  También tengo experiencia en la resolución y gestión de proyectos académicos, con habilidades blandas para comunicarme con efectividad con el grupo de trabajo y
  dirigir así como seguir la línea base planteada, evitando los conflictos y retrasos con las entregas.
skills:
  - "Python"
  - "C++"
  - "JavaScript"
  - "Git y GitHub"
  - "React"
  - "Metodologías Ágiles (Scrum)"
  - "Java"
  - "Resolución de problemas técnicos"

education:
  - institution: "Universidad Francisco de Paula Santander (UFPS)"
    degree: "Ingeniería de Sistemas"
    start_date: "2022-01"
    end_date: "2027-01"
    achievements:
      - "Promedio general sobresaliente: 4.01/5.0."
      - "Desarrollo de página web junto con un equipo de 3 compañeros para contener información de una Fundación."
      

experiences:
 
  - company: "Facultad de Ingeniería, UFPS"
    role: "Ayudante del área de UVirtual"
    start_date: "2026-02"
    end_date: "2025-06"
    achievements:
      - "Ayudé en la labor de gestión de información de la plataforma UVirtual, facilitando el acceso a recursos académicos para estudiantes y profesores."

  - company: "Facultad de Ingeniería, UFPS"
    role: "Desarrolladora frontend y tester de proyectos académicos"
    start_date: "2023-02"
    end_date: "2026-06"
    achievements:
      - "Trabajé desarrollando páginas web con compañeros y enfocándome en pruebas unitarias, así como la documentación de los resultados y errores."